### ISSUE TITLE
`get` with no kube server running takes a while to return

### ISSUE THREAD

**Issue by tobias** [projectodd/kubernetes#22]
We should figure out why a naked `get` even hits the server, and when the server isn't available, giving an appropriate message.

**Comment by tobias** [comment]
Hmm, the plot thickens. I started the minikube instance, and a naked `get` now returns immediately asking for a resource type. If I give it one, I get `The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?`. Which indicates that kube isn't actually running on the machine. But why the different behavior?

**Comment by tobias** [comment]
Ah, probably because with the server up but the port not bound, the connection is refused immediately vs a timeout. And whatever is triggering the network access for the naked `get` isn't reporting the connection failure.

**Comment by bbrowning** [comment]
I resolved this a while back (but forgot to close the issue) with the introduction of a TimeoutFinder for completions.
